# Foundations of AI & ML
## Session 08
### Experiment 3 Part 2

### Leave One Out

Leave One Out is a special form of Cross-Validation. In this method each sample is used once as a test set while the remaining samples for the training set. A generalization error estimate is obtained by repeating this procedure for each of the training points available, averaging the results.

In this experiment we are going to apply LOO on the MNIST dataset and then tune the hyper parameters of MLPClassifier.

#### Importing the packages

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import LeaveOneOut

In [2]:
## Loading the dataset
digits = datasets.load_digits(n_class=10)
## storing the data in x
X = digits.data
## Storing the target data into y
y = digits.target

In [3]:
len(X)

1797

In [4]:
# Creating the object
loo = LeaveOneOut()
#Returns the number of splitting iterations in the cross-validator
loo.get_n_splits(X)


1797

In [5]:
### hyper parameters
# activation
a = ["identity", "logistic", "tanh", "relu"]
#solvers
s = ["lbfgs", "sgd", "adam"]
#learning rate
lr = [0.0001, 0.001, 0.01, 0.1]
#hidden layers
h = [(5,2),(3,2),(6,3),(7,2)]

In [6]:
#function to Create MLP classifier object with hyper parameters
def mlp(a,s,h,lr):
    clf = MLPClassifier(activation= a ,solver= s ,hidden_layer_sizes = h,max_iter = 5000 ,learning_rate = 'constant',learning_rate_init=lr)
    return clf 
#function to calculate the accuracy
def accuracy(actual,predicted):
    return np.count_nonzero(actual == predicted)*1.0/len(actual)

** Exercise 1 ** Predict the values on the trained model using test data and calculate the accuracy

In [7]:
for train_index, test_index in loo.split(X):
    print(train_index, test_index)

[   1    2    3 ... 1794 1795 1796] [0]
[   0    2    3 ... 1794 1795 1796] [1]
[   0    1    3 ... 1794 1795 1796] [2]
[   0    1    2 ... 1794 1795 1796] [3]
[   0    1    2 ... 1794 1795 1796] [4]
[   0    1    2 ... 1794 1795 1796] [5]
[   0    1    2 ... 1794 1795 1796] [6]
[   0    1    2 ... 1794 1795 1796] [7]
[   0    1    2 ... 1794 1795 1796] [8]
[   0    1    2 ... 1794 1795 1796] [9]
[   0    1    2 ... 1794 1795 1796] [10]
[   0    1    2 ... 1794 1795 1796] [11]
[   0    1    2 ... 1794 1795 1796] [12]
[   0    1    2 ... 1794 1795 1796] [13]
[   0    1    2 ... 1794 1795 1796] [14]
[   0    1    2 ... 1794 1795 1796] [15]
[   0    1    2 ... 1794 1795 1796] [16]
[   0    1    2 ... 1794 1795 1796] [17]
[   0    1    2 ... 1794 1795 1796] [18]
[   0    1    2 ... 1794 1795 1796] [19]
[   0    1    2 ... 1794 1795 1796] [20]
[   0    1    2 ... 1794 1795 1796] [21]
[   0    1    2 ... 1794 1795 1796] [22]
[   0    1    2 ... 1794 1795 1796] [23]
[   0    1    2 ... 1794 1

[   0    1    2 ... 1794 1795 1796] [500]
[   0    1    2 ... 1794 1795 1796] [501]
[   0    1    2 ... 1794 1795 1796] [502]
[   0    1    2 ... 1794 1795 1796] [503]
[   0    1    2 ... 1794 1795 1796] [504]
[   0    1    2 ... 1794 1795 1796] [505]
[   0    1    2 ... 1794 1795 1796] [506]
[   0    1    2 ... 1794 1795 1796] [507]
[   0    1    2 ... 1794 1795 1796] [508]
[   0    1    2 ... 1794 1795 1796] [509]
[   0    1    2 ... 1794 1795 1796] [510]
[   0    1    2 ... 1794 1795 1796] [511]
[   0    1    2 ... 1794 1795 1796] [512]
[   0    1    2 ... 1794 1795 1796] [513]
[   0    1    2 ... 1794 1795 1796] [514]
[   0    1    2 ... 1794 1795 1796] [515]
[   0    1    2 ... 1794 1795 1796] [516]
[   0    1    2 ... 1794 1795 1796] [517]
[   0    1    2 ... 1794 1795 1796] [518]
[   0    1    2 ... 1794 1795 1796] [519]
[   0    1    2 ... 1794 1795 1796] [520]
[   0    1    2 ... 1794 1795 1796] [521]
[   0    1    2 ... 1794 1795 1796] [522]
[   0    1    2 ... 1794 1795 1796

[   0    1    2 ... 1794 1795 1796] [988]
[   0    1    2 ... 1794 1795 1796] [989]
[   0    1    2 ... 1794 1795 1796] [990]
[   0    1    2 ... 1794 1795 1796] [991]
[   0    1    2 ... 1794 1795 1796] [992]
[   0    1    2 ... 1794 1795 1796] [993]
[   0    1    2 ... 1794 1795 1796] [994]
[   0    1    2 ... 1794 1795 1796] [995]
[   0    1    2 ... 1794 1795 1796] [996]
[   0    1    2 ... 1794 1795 1796] [997]
[   0    1    2 ... 1794 1795 1796] [998]
[   0    1    2 ... 1794 1795 1796] [999]
[   0    1    2 ... 1794 1795 1796] [1000]
[   0    1    2 ... 1794 1795 1796] [1001]
[   0    1    2 ... 1794 1795 1796] [1002]
[   0    1    2 ... 1794 1795 1796] [1003]
[   0    1    2 ... 1794 1795 1796] [1004]
[   0    1    2 ... 1794 1795 1796] [1005]
[   0    1    2 ... 1794 1795 1796] [1006]
[   0    1    2 ... 1794 1795 1796] [1007]
[   0    1    2 ... 1794 1795 1796] [1008]
[   0    1    2 ... 1794 1795 1796] [1009]
[   0    1    2 ... 1794 1795 1796] [1010]
[   0    1    2 ... 179

[   0    1    2 ... 1794 1795 1796] [1485]
[   0    1    2 ... 1794 1795 1796] [1486]
[   0    1    2 ... 1794 1795 1796] [1487]
[   0    1    2 ... 1794 1795 1796] [1488]
[   0    1    2 ... 1794 1795 1796] [1489]
[   0    1    2 ... 1794 1795 1796] [1490]
[   0    1    2 ... 1794 1795 1796] [1491]
[   0    1    2 ... 1794 1795 1796] [1492]
[   0    1    2 ... 1794 1795 1796] [1493]
[   0    1    2 ... 1794 1795 1796] [1494]
[   0    1    2 ... 1794 1795 1796] [1495]
[   0    1    2 ... 1794 1795 1796] [1496]
[   0    1    2 ... 1794 1795 1796] [1497]
[   0    1    2 ... 1794 1795 1796] [1498]
[   0    1    2 ... 1794 1795 1796] [1499]
[   0    1    2 ... 1794 1795 1796] [1500]
[   0    1    2 ... 1794 1795 1796] [1501]
[   0    1    2 ... 1794 1795 1796] [1502]
[   0    1    2 ... 1794 1795 1796] [1503]
[   0    1    2 ... 1794 1795 1796] [1504]
[   0    1    2 ... 1794 1795 1796] [1505]
[   0    1    2 ... 1794 1795 1796] [1506]
[   0    1    2 ... 1794 1795 1796] [1507]
[   0    1 

In [ ]:
test_accuracy = []
train_accuracy = []
for i in range(10):
    k1 = np.random.randint(0,len(a))
    k2 = np.random.randint(0,len(s))
    k3 = np.random.randint(0,len(lr))
    k4 = np.random.randint(0,len(h))
    print("\nHyper-parameters = \n activation = ", a[k1],    "\n solver = ", s[k2], "\n learning_rate_init = ", lr[k3],         "\n hidden_layer_sizes = ", h[k4])
    #calling the mlp function with random hyper paramters
    clf = mlp(a[k1],s[k2],h[k4],lr[k3])
    tempTrain = 0
    tempTest = 0
    for train_index, test_index in loo.split(X):
    ## Splitting the data into train and test
        X_train, X_test = X[train_index], X[test_index]
        Y_train, Y_test = y[train_index], y[test_index]
        ##fit the data into the model
        clf.fit(X_train, Y_train)
        ##predicting the values on the fitted model
        predTrain = clf.predict((X_train))
        ##Calculating the train accuracy
        tempTrain = tempTrain + accuracy(Y_train,predTrain)
        ##predict the values on the fitted model using test data
        predTest = clf.predict((X_test))
        ##Calculating the test accuracy
        tempTest = tempTest + accuracy(Y_test, predTest)
    ##Calculating the train accuracy
    train_accuracy.append(tempTrain * 1.0 / 1797)
    ##Calculating the test accuracy
    test_accuracy.append(tempTest * 1.0 / 1797)
    print("(train,test) accuracy = ",tempTrain*1.0, tempTest*1.0)


Hyper-parameters = 
 activation =  relu 
 solver =  lbfgs 
 learning_rate_init =  0.01 
 hidden_layer_sizes =  (7, 2)


In [ ]:
#Plotting the data
xx = np.array(range(1,11))
plt.bar(xx-0.2,train_accuracy,width=0.2)
plt.bar(xx, test_accuracy,width=0.2)
plt.legend(["Train","Test"])
plt.show()

**Exercise 2** vary the hidden layers, learning rate values  and observe the changes

In [ ]:
we 

**Solutions**

**Exercise 1 **

In [ ]:
predTest = clf.predict((X_test))
tempTest = tempTest + accuracy(Y_test,predTest)

**Exercise 2 **

In [ ]:
#learning rate
lr = [0.0001,0.001,0.01,0.1,0.002,0.2]
#hidden layers
h = [(5,4),(9,2),(4,8),(7,5)]